version: '3.4'

services:
  postgres:
    container_name: condominioDatabase
    user: postgres
    environment:
      POSTGRES_PASSWORD: docker
      PGUSER: postgres
      POSTGRES_DB: condominioDatabase
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - C:/Docker/Banco:/var/lib/postgresql/data
    networks:
      - mynetwork
  condominio.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8080:80
    volumes:
      - C:/Docker/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - C:/Docker/ASP.NET/Https:/root/.aspnet/https:ro
    links:
      - postgres
    depends_on:
      postgres:
         condition: service_healthy
    command: ["./wait-for-it.sh", "postgres:5432", "--", "python", "app.py"] 
    networks:
    - mynetwork
networks:
  mynetwork:
     driver: bridge